version: 1
accounts:
  - name: alice
    coins: ["2000000000uqbit", "100000000000000ugoi"]
  - name: bob
    coins: ["500000000uqbit"]
  - name: deke
    coins: ["500000000uqbit", "100000000ugoi"]
    address: qbit18uhwjwjh0a2we39cv4k7jgqzv5xgmzgdw2kyjn
  - name: bang
    coins: ["10000000uqbit"]
    address: qbit16306skfzgu2wfcedj0d4zw6h2cfy3juz54gyed
validator:
  name: alice
  staked: "50000000000000ugoi"
faucet:
  name: bob
  coins:
    - "500000000uqbit"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
genesis:
  chain_id: "qbit-1"
  app_state:
    staking:
      params:
        bond_denom: "ugoi"

build:
  binary: qbit
init:
  home: ./qbit-gateway