// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: xAction.proto

package proto_vendor

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActionOrContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*ActionOrContract_Action
	//	*ActionOrContract_Contract
	Data isActionOrContract_Data `protobuf_oneof:"data"`
}

func (x *ActionOrContract) Reset() {
	*x = ActionOrContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xAction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionOrContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionOrContract) ProtoMessage() {}

func (x *ActionOrContract) ProtoReflect() protoreflect.Message {
	mi := &file_xAction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionOrContract.ProtoReflect.Descriptor instead.
func (*ActionOrContract) Descriptor() ([]byte, []int) {
	return file_xAction_proto_rawDescGZIP(), []int{0}
}

func (m *ActionOrContract) GetData() isActionOrContract_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ActionOrContract) GetAction() *XAction {
	if x, ok := x.GetData().(*ActionOrContract_Action); ok {
		return x.Action
	}
	return nil
}

func (x *ActionOrContract) GetContract() *ContractResponse {
	if x, ok := x.GetData().(*ActionOrContract_Contract); ok {
		return x.Contract
	}
	return nil
}

type isActionOrContract_Data interface {
	isActionOrContract_Data()
}

type ActionOrContract_Action struct {
	Action *XAction `protobuf:"bytes,1,opt,name=action,proto3,oneof"`
}

type ActionOrContract_Contract struct {
	Contract *ContractResponse `protobuf:"bytes,2,opt,name=contract,proto3,oneof"`
}

func (*ActionOrContract_Action) isActionOrContract_Data() {}

func (*ActionOrContract_Contract) isActionOrContract_Data() {}

type XAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Data        []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Blockheight []byte `protobuf:"bytes,3,opt,name=blockheight,proto3" json:"blockheight,omitempty"`
}

func (x *XAction) Reset() {
	*x = XAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xAction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAction) ProtoMessage() {}

func (x *XAction) ProtoReflect() protoreflect.Message {
	mi := &file_xAction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAction.ProtoReflect.Descriptor instead.
func (*XAction) Descriptor() ([]byte, []int) {
	return file_xAction_proto_rawDescGZIP(), []int{1}
}

func (x *XAction) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *XAction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XAction) GetBlockheight() []byte {
	if x != nil {
		return x.Blockheight
	}
	return nil
}

type ContractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Warning, if data is set, writes the contract and sends no reply, else reads.
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TypeName []byte `protobuf:"bytes,3,opt,name=typeName,proto3" json:"typeName,omitempty"`
}

func (x *ContractRequest) Reset() {
	*x = ContractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xAction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRequest) ProtoMessage() {}

func (x *ContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xAction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRequest.ProtoReflect.Descriptor instead.
func (*ContractRequest) Descriptor() ([]byte, []int) {
	return file_xAction_proto_rawDescGZIP(), []int{2}
}

func (x *ContractRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ContractRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContractRequest) GetTypeName() []byte {
	if x != nil {
		return x.TypeName
	}
	return nil
}

type ContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TypeName []byte `protobuf:"bytes,3,opt,name=typeName,proto3" json:"typeName,omitempty"`
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xAction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xAction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_xAction_proto_rawDescGZIP(), []int{3}
}

func (x *ContractResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ContractResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContractResponse) GetTypeName() []byte {
	if x != nil {
		return x.TypeName
	}
	return nil
}

var File_xAction_proto protoreflect.FileDescriptor

var file_xAction_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x78, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x10,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x12, 0x2d, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x78, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x59, 0x0a, 0x07, 0x78, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x5b,
	0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5c, 0x0a, 0x10, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x5e, 0x0a, 0x0a, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x50, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_xAction_proto_rawDescOnce sync.Once
	file_xAction_proto_rawDescData = file_xAction_proto_rawDesc
)

func file_xAction_proto_rawDescGZIP() []byte {
	file_xAction_proto_rawDescOnce.Do(func() {
		file_xAction_proto_rawDescData = protoimpl.X.CompressGZIP(file_xAction_proto_rawDescData)
	})
	return file_xAction_proto_rawDescData
}

var file_xAction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xAction_proto_goTypes = []interface{}{
	(*ActionOrContract)(nil), // 0: appConnect.ActionOrContract
	(*XAction)(nil),          // 1: appConnect.xAction
	(*ContractRequest)(nil),  // 2: appConnect.ContractRequest
	(*ContractResponse)(nil), // 3: appConnect.ContractResponse
}
var file_xAction_proto_depIdxs = []int32{
	1, // 0: appConnect.ActionOrContract.action:type_name -> appConnect.xAction
	3, // 1: appConnect.ActionOrContract.contract:type_name -> appConnect.ContractResponse
	0, // 2: appConnect.AppConnect.ExecuteAction:input_type -> appConnect.ActionOrContract
	2, // 3: appConnect.AppConnect.ExecuteAction:output_type -> appConnect.ContractRequest
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xAction_proto_init() }
func file_xAction_proto_init() {
	if File_xAction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xAction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionOrContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xAction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xAction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xAction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_xAction_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ActionOrContract_Action)(nil),
		(*ActionOrContract_Contract)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xAction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xAction_proto_goTypes,
		DependencyIndexes: file_xAction_proto_depIdxs,
		MessageInfos:      file_xAction_proto_msgTypes,
	}.Build()
	File_xAction_proto = out.File
	file_xAction_proto_rawDesc = nil
	file_xAction_proto_goTypes = nil
	file_xAction_proto_depIdxs = nil
}
